set_property SRC_FILE_INFO {cfile:C:/Users/SaikotDasJoy/Desktop/Embedded_Electronics_B/project_28/project_28.srcs/constrs_1/new/cons.xdc rfile:../../../project_28.srcs/constrs_1/new/cons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J2    IOSTANDARD LVCMOS33 } [get_ports { IR_sensor_jc_sda_io }]; #IO_L22N_T3_35 Sch=jc[3]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G6    IOSTANDARD LVCMOS33 } [get_ports { IR_sensor_jc_scl_io }]; #IO_L19P_T3_35 Sch=jc[4]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G1    IOSTANDARD LVCMOS33 } [get_ports { SpO2_Pulse_Sensor_jd_scl_io }]; #IO_L17N_T2_35 Sch=jd[3]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G3    IOSTANDARD LVCMOS33 } [get_ports { SpO2_Pulse_Sensor_jd_sda_io }]; #IO_L20N_T3_35 Sch=jd[4]
